- name: install the latest version of Nginx
  yum:
    name: nginx
    state: latest

- name: Copy nginx.conf
  template:
    src: "templates/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
  notify: restart_nginx

- name: Start and enable Nginx service
  systemd:
    name: nginx
    state: started
    enabled: true
    daemon_reload: true
