- name: Check that we can connect (GET) to a page and it returns a status 200
  hosts: box
  remote_user: vagrant

  tasks:
    # Check that you can connect (GET) to a page and it returns a status 200
    - uri: url=http://127.0.0.1/myapp

    # Check that a page returns a status 200 and fail if the word mnt-exam is not in the page contents.
    - action: uri url=http://127.0.0.1/myapp return_content=yes
      register: webpage

    - action: fail
      when: '"mnt-exam" not in webpage.content'
