- hosts: localhost
  connection: local

  vars:
    mongo_src:
    - http://downloads.mongodb.org/linux/mongodb-linux-arm64-ubuntu1604-latest.tgz
    -  http://downloads.mongodb.org/linux/mongodb-linux-x86_64-debian71-v3.4-latest.tgz
    -  http://downloads.mongodb.org/linux/mongodb-linux-x86_64-debian71-v3.2-latest.tgz
    -  http://downloads.mongodb.org/linux/mongodb-linux-x86_64-suse12-v3.4-latest.tgz
    -  http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel70-latest.tgz
    -  http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel62-v3.4-latest.tgz
    -  http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel55-v3.2-latest.tgz
    -  http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel62-v3.2-latest.tgz
    -  http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel62-v3.0-latest.tgz

  tasks:
  - debug: msg={{ mongo_src | get_mongo_src("rhel", "7", "3.2" ) }}
  - debug: msg={{ mongo_src | get_mongo_src("rhel", "6", "3.0" ) }}
  - debug: msg={{ mongo_src | get_mongo_src("rhel", "7", "3.4" ) }}
